pipeline:
  build:
    image: nixos/nix
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      # Lint
      - nix develop --command cargo -- fmt --all -- --check
      - nix develop --command cargo -- clippy -- -D warnings -W clippy::must_use_candidate
      - nix develop .#ci --command alejandra -- --check .
      - nix develop .#ci --command markdown-link-check README.md
      # Test
      - nix develop --command cargo test --verbose --release
      - nix develop --command cargo test --verbose
      # Run through Nix
      - nix build
      - nix run

when:
  evaluate: '(CI_BUILD_EVENT == "push" && CI_COMMIT_BRANCH == CI_REPO_DEFAULT_BRANCH) || (CI_BUILD_EVENT == "pull_request")'
